config/routes.rb
Rails.application.routes.draw do
  get 'comments/create'
  devise_for :users, controllers: { omniauth_callbacks: "omniauth_callbacks" }
  resources :finish_signup, only: [:edit, :update]
  resources :pins
  resources :posts
  get 'pages/index'
  get 'pages/about'
  get 'pages/us'
  get "pages/index"

  resources :posts do
    member do
      get 'upvote'
    end
    resources :comments, only: :create 
  end

  root 'pages#index'
  get 'mypins' => 'pins#mypins'
  get 'pinsof/:user_id' => 'pins#pinsof', :as => "pinsof"

end

app/models/pin.rb
class Pin < ActiveRecord::Base
validates :photo, presence:true
validates :description, presence:true

belongs_to :user
end

app/controllers/pins_controller.rb
class PinsController < ApplicationController
  before_action :set_pin, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_user!, except: [ :index, :show]
  
  def pinsof
    @user_id = params[:user_id]
    @user = User.find(@user_id)
    @pins = @user.pins
  end

  def mypins
    @pins = current_user.pins 
  end


  # GET /pins
  # GET /pins.json
  def index
    @pins = Pin.all
  end

  # GET /pins/1
  # GET /pins/1.json
  def show
  end

  # GET /pins/new
  def new
    @pin = Pin.new
  end

  # GET /pins/1/edit
  def edit
  end

  # POST /pins
  # POST /pins.json
  def create
    @pin = Pin.new(pin_params)
    @pin.user_id = current_user.id
    respond_to do |format|
      if @pin.save
        format.html { redirect_to @pin, notice: 'Pin was successfully created.' }
        format.json { render :show, status: :created, location: @pin }
      else
        format.html { render :new }
        format.json { render json: @pin.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pins/1
  # PATCH/PUT /pins/1.json
  def update
    respond_to do |format|
      if @pin.update(pin_params)
        format.html { redirect_to @pin, notice: 'Pin was successfully updated.' }
        format.json { render :show, status: :ok, location: @pin }
      else
        format.html { render :edit }
        format.json { render json: @pin.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pins/1
  # DELETE /pins/1.json
  def destroy
    @pin.destroy
    respond_to do |format|
      format.html { redirect_to pins_url, notice: 'Pin was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pin
      @pin = Pin.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pin_params
      params.require(:pin).permit(:photo, :description, :name)
    end
  end

app/helpers/pins_helper.rb
module PinsHelper
end

app/views/pins/_form.html.erb
<%= form_for(@pin) do |f| %>
  <% if @pin.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@pin.errors.count, "error") %> prohibited this pin from being saved:</h2>

      <ul>
      <% @pin.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
     <div class="field">
    <%= f.label :name, "Nombre" %><br>
    <%= f.text_field :name, :class => 'form-control', :placeholder => "Nombre del Pin" %>
  </div>
  </div>

 <div class="form-group">
  <div class="field">
    <%= f.label :photo, "Foto" %><br>
    <%= f.text_field :photo, :class => 'form-control', :placeholder => "URL de la foto" %>
  </div>
  </div>

   <div class="form-group">
  <div class="field">
    <%= f.label :description, "Descripción" %><br>
    <%= f.text_area :description, :class => 'form-control', :rows => "10", :cols => "30" %>
  </div>
  </div>

 

  <div class="actions">
    <%= f.submit "Crear", :class => "btn btn-primary" %>
  </div>
  </div>
<% end %>

app/views/pins/edit.html.erb
<div class="container">
	<div class="row">
		<div class col-md-6>
			<h1>Editing Pin</h1>
			<%= render 'form' %>
		</div>
		
	</div>

	<%= link_to 'Show', @pin %> |
	<%= link_to 'Back', pins_path %>
</div>

app/views/pins/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Pins</h1>

<table>
  <thead>
    <tr>
      <th>Photo</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @pins.each do |pin| %>
      <tr>
        <td><%= pin.photo %></td>
        <td><%= pin.description %></td>
        <td><%= link_to 'Show', pin %></td>
        <td><%= link_to 'Edit', edit_pin_path(pin) %></td>
        <td><%= link_to 'Destroy', pin, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Pin', new_pin_path %>

app/views/pins/mypins.html.erb
<div class="container">
  <h1>Mis pins</h1>

  <% @pins.each do |pin| %>
  <div class="col-md-3">
    <div class="thumbnail">
      <%= pin.name %>
      <%= image_tag(pin.photo, :class => 'img-responsive') %> 
      <%= pin.description %>

     <div class="buttons" style="margin-top:10px; margin-bottom:10px">
      <%= link_to 'Show', pin %>
      <%= link_to 'Edit', edit_pin_path(pin) %>
      <% if user_signed_in? %>
      <%= link_to 'Destroy', pin, method: :delete, data: { confirm: 'Are you sure?' } %>
      <% end %>
    </div>
  </div>
</div>
<% end %>

<br>
<% if user_signed_in? %>
<%= link_to 'New Pin', new_pin_path %>
<% end %>

</div>

app/views/pins/new.html.erb
<div class="container">
	

<h1>Agrega nuevo pin</h1>
<div class="row">
<div class="col-md-6">
	

<%= render 'form' %>
</div>
</div>

<p> <%= link_to 'Back', pins_path %> </p>

</div>

app/views/pins/pinsof.html.erb
<%= @user_id %>

app/views/pins/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @pin.name %>
</p>

<p>
  <strong>Photo:</strong>
  <%= image_tag(@pin.photo, :style => 'width:250px') %>
</p>

<p>
  <strong>Description:</strong>
  <%= @pin.description %>
</p>

<%= link_to 'Edit', edit_pin_path(@pin) %> |
<%= link_to 'Back', pins_path %>

<%= link_to "Mas fotos del mismo usuario", pinsof_path(@pin.user.id) %>