config/routes.rb
Rails.application.routes.draw do
  get 'comments/create'
  devise_for :users, controllers: { omniauth_callbacks: "omniauth_callbacks" }
  resources :finish_signup, only: [:edit, :update]
  resources :pins
  resources :posts
  get 'pages/index'
  get 'pages/about'
  get 'pages/us'
  get "pages/index"

  resources :posts do
    member do
      get 'upvote'
    end
    resources :comments, only: :create 
  end

  root 'pages#index'
  get 'mypins' => 'pins#mypins'
  get 'pinsof/:user_id' => 'pins#pinsof', :as => "pinsof"

end

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-default" style="margin-bottom: 0px">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="<%= pages_index_path %>">Home</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><a href="#">Nosotros<span class="sr-only">(current)</span></a></li>
        <li><a href="<%= mypins_path %>"> Mis Pins</a></li>

        <li><a href="pins">Photos</a></li>
        <li><a href="posts">Posts</a></li>
        
      </ul>

       <form class="navbar-form navbar-left" role="search">
        <div class="form-group">
          <input name="q" type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form>
      

      <ul class="nav navbar-nav navbar-right">
        <% if  current_user.nil?%>
        <li><a href="<%= new_user_session_path %>">Ingresar</a></li>
        <li><a href="<%= new_user_registration_path %>">Registrar</a></li>
        <% else %>
              <li>
        <%= current_user.email %>

      </li>
        <li><a href="<%= destroy_user_session_path %>" data-method="DELETE">Salir</a></li>
        <% end %>
      </ul>

      <ul class="hmenu">
        <%= render 'devise/menu/login_items' %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>