config/routes.rb
Rails.application.routes.draw do
  get 'comments/create'
  devise_for :users, controllers: { omniauth_callbacks: "omniauth_callbacks" }
  resources :finish_signup, only: [:edit, :update]
  resources :pins
  resources :posts
  get 'pages/index'
  get 'pages/about'
  get 'pages/us'
  get "pages/index"

  resources :posts do
    member do
      get 'upvote'
    end
    resources :comments, only: :create 
  end

  root 'pages#index'
  get 'mypins' => 'pins#mypins'
  get 'pinsof/:user_id' => 'pins#pinsof', :as => "pinsof"

end

app/controllers/finish_signup_controller.rb
class FinishSignupController < ApplicationController
	before_action :load_user, only: [:edit, :update]
	
	def edit
	end
	def update
		
		if @user.update(user_params)
			sign_in(@user, bypass: true)
			redirect_to root_path, notice: "Email updated successfully!"
		else
			render :edit
		end
		
	end
	
	private
	
	def load_user
		@user ||= User.find(params[:id])
	end
	
	def user_params
		params.require(:user).permit(:email)
	end
end

app/views/finish_signup/edit.html.erb
<h1>Confirma tu Email</h1>
<%= form_for(@user, as: 'user', url: finish_signup_path(id: current_user, method: :patch)) do |f| %>
	
	<% if @user.errors.any? %>
	
	<h2>Errores encontrados:</h2>
	
	<ul>
		<% @user.errors.full_messages.each do |msg| %>
		<li><%= msg %></li>
		<% end %>
	</ul>
	<% end %>
	
	<div>
		<%= f.label :email %>
		<%= f.text_field :email, autofocus: true, value: '', placeholder: 'Example: email@me.com' %>
	</div>
	
	<div>
		<%= f.submit 'Confirmar' %>
	</div>
	<% end %>