config/routes.rb
Rails.application.routes.draw do
  get 'comments/create'
  devise_for :users, controllers: { omniauth_callbacks: "omniauth_callbacks" }
  resources :finish_signup, only: [:edit, :update]
  resources :pins
  resources :posts
  get 'pages/index'
  get 'pages/about'
  get 'pages/us'
  get "pages/index"

  resources :posts do
    member do
      get 'upvote'
    end
    resources :comments, only: :create 
  end

  root 'pages#index'
  get 'mypins' => 'pins#mypins'
  get 'pinsof/:user_id' => 'pins#pinsof', :as => "pinsof"

end

app/models/post.rb
class Post < ActiveRecord::Base
	belongs_to :user
	has_many :comments, dependent: :destroy
	has_many :votes, as: :votable
	has_many :users_who_voted, through: :votes, :source => :user
	mount_uploader :photo, PictureUploader
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  load_and_authorize_resource

# GET /posts
# GET /posts.json
def index

  @q = params[:q]
  if params[:q]
    @posts = Post.where(title:@q)
  else
    @posts = Post.all
  end
end

# GET /posts/1
# GET /posts/1.json
def show
  @last_comments = @post.comments.last(5)
  @comment = @post.comments.build
end

# GET /posts/new
def new
  @post = Post.new
end

# GET /posts/1/edit
def edit
end

# POST /posts
# POST /posts.json
def create
  @post = Post.new(post_params)

  respond_to do |format|
    if @post.save
      format.html { redirect_to @post, notice: 'Post was successfully created.' }
      format.json { render :show, status: :created, location: @post }
    else
      format.html { render :new }
      format.json { render json: @post.errors, status: :unprocessable_entity }
    end
  end
end

# PATCH/PUT /posts/1
# PATCH/PUT /posts/1.json
def update
  respond_to do |format|
    if @post.update(post_params)
      format.html { redirect_to @post, notice: 'Post was successfully updated.' }
      format.json { render :show, status: :ok, location: @post }
    else
      format.html { render :edit }
      format.json { render json: @post.errors, status: :unprocessable_entity }
    end
  end
end

# DELETE /posts/1
# DELETE /posts/1.json
def destroy
  @post.destroy
  respond_to do |format|
    format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
    format.json { head :no_content }
  end
end


def upvote
  @vote = Vote.find_or_initialize_by(user: current_user, post: @post)
  return destroy_and_redirect if @vote.persisted?
  save_and_redirect
end

private


def save_and_redirect
  if @vote.save
    redirect_to @post, notice: "Tu voto fue creado exitosamente"
  else
    redirect_to @post, notice: @vote.errors.full_messages.join(", ")
  end
end

def destroy_and_redirect
  @vote.destroy
  redirect_to @post, notice: "Tu voto ha sido anulado!!"
end


  # Use callbacks to share common setup or constraints between actions.
  def set_post
    @post = Post.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def post_params
    params.require(:post).permit(:title, :content, :photo, :photo_cache)
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<%= form_for(@post, html: {multipart: true}) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>



  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :content %><br>
    <%= f.text_area :content %>
  </div>
  <div class="field">
    <%= f.label :photo %><br>
    <%= f.file_field :photo %>
    <%= f.hidden_field :photo_cache %>
    <%= image_tag(@post.photo, size: "16x10") if @post.photo? %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Posts</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Content</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= post.title %></td>
        <td><%= post.content %></td>
        <td><%= image_tag(post.photo.thumb, size: "320x200") %></td>
        <td><%= link_to 'Show', post %></td>

<% if can?(:edit, @post) %>
        <td><%= link_to 'Edit', edit_post_path(post) %></td>

        <% end %>
        <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Post', new_post_path %>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form' %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
	<strong>Title:</strong>
	<%= @post.title %>
</p>

<p>
	<strong>Content:</strong>
	<%= @post.content %>
</p>



<p>
	<strong>Votes:</strong>
	<%= @post.votes.count %>
</p>


<%= form_for [@post, @comment] do |f| %>
<%= f.label :content %>
<%= f.text_area :content %>

<%= f.submit "Publish comment" %>
<% end %>

<% @post.comments.find_each do |c| %>
<%= c.content %>
<% end %>

<%= link_to "+1", upvote_post_path(@post) %>

<% if can?(:edit, @post) %>
<%= link_to 'Edit', edit_post_path(@post) %> |
<% end %>
<%= link_to 'Back', posts_path %>

<%= render 'comments/form' %>
<%= render partial: "comments/comment", collection: @last_comments %>